import type { StemsResponse } from './api';

/**
 * Devuelve una copia de StemsResponse sin el grupo indicado.
 * Útil para actualizar la UI inmediatamente tras borrar un grupo.
 */
export function removeGroup(stems: StemsResponse | null, song: string): StemsResponse | null {
  if (!stems || !stems.output || !(song in stems.output)) return stems;
  const next = { ...stems, output: { ...stems.output } };
  delete next.output[song];
  return next;
}

// Filename prefixes generated by Onda export endpoints. These files are not
// separable stems and must not appear in the export/stem list.
const exportFilePrefixes = ['merge_', 'export_'];
const exportFileNames = new Set(['export.mid']);

/**
 * Reports whether a filename corresponds to an exported mixdown or MIDI file
 * rather than a source stem. Used to hide legacy exports that may still live
 * next to the stems.
 */
export function isExportFileName(name: string): boolean {
  if (exportFileNames.has(name)) return true;
  const lower = name.toLowerCase();
  return exportFilePrefixes.some((prefix) => lower.startsWith(prefix));
}

/**
 * Returns a copy of StemsResponse with known export filenames removed from
 * every group's stem list. This is a client-side safety net in case the
 * backend ever returns an export file alongside stems.
 */
export function filterExportFileNames(stems: StemsResponse | null): StemsResponse | null {
  if (!stems || !stems.output) return stems;
  const next: StemsResponse = { ...stems, output: {} };
  for (const [song, list] of Object.entries(stems.output)) {
    next.output[song] = list.filter((name) => !isExportFileName(name));
  }
  return next;
}
